services:
  app:
    image: webgoat/webgoat:v2023.8@sha256:01672eb9aeba60d042ae1131d6de683b98fa64e9da60fa5d3daad2642a6795dd
    ports:
      - "127.0.0.1:18081:8080"
    environment:
      WEBGOAT_HOST: 127.0.0.1
      WEBGOAT_PORT: 8080
    restart: "no"
    networks:
      - lab

networks:
  lab:
    internal: true
