import assert from "node:assert/strict";
import test from "node:test";
import { companionSystemPrompt } from "./system-prompt.js";

test("companion default prompt follows the UI locale", () => {
  const chinese = companionSystemPrompt("zh");
  assert.match(chinese, /始终用简体中文/);
  assert.match(chinese, /你是 MilkSU 看板娘/);
  assert.match(chinese, /companion_board/);
  assert.match(chinese, /companion_dispatch/);
  assert.doesNotMatch(chinese, /subagent/);
  assert.match(chinese, /Working/);
  assert.match(chinese, /编排/);
  assert.match(chinese, /companion_app/);
  assert.match(chinese, /speak_many/);
  assert.doesNotMatch(chinese, /You are the MilkSU Companion/);
  assert.doesNotMatch(chinese, /这不是/);
  assert.doesNotMatch(chinese, /不拦/);

  const english = companionSystemPrompt("en");
  assert.match(english, /You are the MilkSU Companion/);
  assert.match(english, /companion_board/);
  assert.match(english, /companion_dispatch/);
  assert.doesNotMatch(english, /subagent/);
  assert.match(english, /Working/);
  assert.match(english, /orchestrat/i);
  assert.match(english, /companion_app/);
  assert.match(english, /speak_many/);
  assert.doesNotMatch(english, /你是 MilkSU 看板娘/);
  assert.doesNotMatch(english, /this is not/i);
  assert.doesNotMatch(english, /we don't block/i);
  assert.doesNotMatch(chinese, /三个用户回合/);
  assert.doesNotMatch(english, /three user turns/);
  assert.match(chinese, /kind 填 image/);
  assert.match(english, /kind image/);
  assert.match(chinese, /决策是长任务时，以这一档为准/);
  assert.match(chinese, /先用 read、bash、grep、find、ls/);
  assert.match(chinese, /没有现成对话时也派发/);
  assert.doesNotMatch(chinese, /没有合适的对话/);
  assert.match(english, /that decision wins/);
  assert.match(english, /Dispatch even when no conversation exists yet/);
  assert.match(chinese, /不要展开旧任务/);
  assert.match(english, /Do not recap old work/);
  assert.match(chinese, /不要等用户来要这些记忆/);
  assert.match(english, /Do not wait for the user to ask/);
  assert.doesNotMatch(chinese, /短消息/);
  assert.match(chinese, /对话标题/);
  assert.match(english, /conversation titles/);
  assert.doesNotMatch(english, /short messages/);
});

test("chat rhythm is prompt text only in chat mode", () => {
  const chinese = companionSystemPrompt("zh", "chat");
  const english = companionSystemPrompt("en", "chat");
  assert.match(chinese, /短消息/);
  assert.match(chinese, /单独成段/);
  assert.match(english, /short messages/);
  assert.match(english, /own paragraph/);
  assert.match(companionSystemPrompt("zh", "markdown"), /对话标题/);
  assert.doesNotMatch(companionSystemPrompt("zh", "markdown"), /短消息/);
});
